project:
  type: website
  output-dir: docs

website:
  title: "JuliaProgrammingForBiologists"
  page-navigation: true
  bread-crumbs: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - text: "Home"
            file: index.qmd
          - about.qmd
      - section: "Julia tutorials"
        contents:
          - InstallJulia.qmd
          - IntroToJulia.qmd
          - PlutoNotebooks.qmd
          - ControlFlow.qmd
          - Plots.qmd
          - BuildSimulation.qmd
          - MultipleDispatch.qmd
          - Numbers.qmd
          - ArraysAndDataFrames.qmd
          - Randomization.qmd
          - LoadDataAnalyzeGraph.qmd
          - UseVSCode.qmd
          - MoreFunThings.qmd
          - ResourcesForFurtherLearning.qmd
  page-footer: "Copyright 2025, Darren Irwin" 

format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    link-external-newwindow: true



